services:
  gpodder:
    container_name: micro-gpodder-server
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./data
        target: ${APP_HOME}/gpodder-data
    hostname: gpodder.localhost
    ports:
      - 8080:8080
